# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
