# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0002_auto_20161106_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='Mia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='Mib',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='Mic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
