# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0003_auto_20161106_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TableInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableId', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='Mia',
            new_name='mia',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='Mib',
            new_name='mib',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='Mic',
            new_name='mic',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='tableData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratatouille.TableInstance'),
        ),
    ]
