# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0004_auto_20161108_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='tableData',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ratatouille.OrderId'),
        ),
        migrations.AddField(
            model_name='tableinstance',
            name='orderId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ratatouille.OrderId'),
        ),
    ]
