# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0007_auto_20161208_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
