# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratatouille', '0009_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinstance',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
